FROM golang:1.26.5-alpine3.24@sha256:0178a641fbb4858c5f1b48e34bdaabe0350a330a1b1149aabd498d0699ff5fb2 AS builder

ENV GOENV=off \
    GOWORK=off \
    GOTOOLCHAIN=local \
    GOPROXY=https://proxy.golang.org \
    GOSUMDB=sum.golang.org \
    GOPRIVATE="" \
    GONOSUMDB="" \
    GONOPROXY="" \
    GOINSECURE=""

WORKDIR /src

RUN wget --quiet \
        --output-document=/tmp/trivy.tar.gz \
        https://github.com/aquasecurity/trivy/archive/8a32853686209a428179bb3a1688802b25691564.tar.gz \
    && echo '5a922c388846d11345ce8283e4373be312458f002abc667c3cd1f77c43163725  /tmp/trivy.tar.gz' \
        | sha256sum -c - \
    && tar -xzf /tmp/trivy.tar.gz --strip-components=1 -C /src \
    && rm -f /tmp/trivy.tar.gz \
    && echo '4f1207875bb6102121cba9871f7da8af158096e6fff0759a3a37adf1beea7d24  go.mod' \
        | sha256sum -c - \
    && echo '4c0326b979bd53518d23944a1ceed5d177a1c5c792074dd82f0fbb3b98e3a879  go.sum' \
        | sha256sum -c - \
    && grep -Eq '^[[:space:]]+oras\.land/oras-go/v2 v2\.6\.0 // indirect$' go.mod \
    && go mod edit -require=oras.land/oras-go/v2@v2.6.2 \
    && go mod tidy \
    && echo '2a11b375757e277f3a56a3125b8c6adf373241614afeb777ca50264e004a65e2  go.mod' \
        | sha256sum -c - \
    && echo '5340573f39cba663800d92e85b6cac2ae001307c4c1d0b084ae29d4f5fec9831  go.sum' \
        | sha256sum -c - \
    && go mod download all \
    && go mod verify \
    && go list -mod=readonly -m all \
        | sha256sum \
        | grep -F '0f5e6b935f789441b411705543bed99ef41ca57cd10adea7c6a23dd581400767  -'

RUN --network=none CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOEXPERIMENT=jsonv2 \
    go build -trimpath -buildvcs=false -mod=readonly \
        -ldflags="-s -w -buildid= -extldflags '-static' -X github.com/aquasecurity/trivy/pkg/version/app.ver=0.72.0-cheby.1" \
        -o /out/trivy ./cmd/trivy/ \
    && /out/trivy --version | grep -Fx 'Version: 0.72.0-cheby.1' \
    && go version -m /out/trivy \
        | grep -Eq '^[[:space:]]+dep[[:space:]]+oras\.land/oras-go/v2[[:space:]]+v2\.6\.2[[:space:]]+' \
    && echo '30329a9bfa5c4b29e7f0b3552ae7430ef011b73963033e9b028e2003bcd08a39  /out/trivy' \
        | sha256sum -c -

FROM scratch

LABEL io.chebycodex.go="1.26.5" \
      io.chebycodex.trivy.module-graph.sha256="0f5e6b935f789441b411705543bed99ef41ca57cd10adea7c6a23dd581400767" \
      io.chebycodex.trivy.oras-go="v2.6.2" \
      io.chebycodex.trivy.source.sha256="5a922c388846d11345ce8283e4373be312458f002abc667c3cd1f77c43163725" \
      org.opencontainers.image.revision="8a32853686209a428179bb3a1688802b25691564" \
      org.opencontainers.image.source="https://github.com/aquasecurity/trivy" \
      org.opencontainers.image.version="0.72.0-cheby.1"

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WORKDIR /

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /out/trivy /usr/local/bin/trivy

USER 65532:65532
ENTRYPOINT ["/usr/local/bin/trivy"]
